### ISSUE TITLE
[Question] Is it possible to manipulate the index of CardNavigation?

### ISSUE THREAD

**Issue by tjerk-git** [nhoogendoorn/CardStack#11]
Hi! I've been using your library, not that advanced with SwiftUI yet.

Is it possible to alter the  @Published var currentIndex: Int = .zero in the CardNavigation?

I want it to be possible to start from a random index (shuffle the cards so the speak).

https://github.com/tjerk-git/YFTP/blob/main/YFTP/Views/StackExampleView.swift

Thanks for making the package, exactly what I needed :)

Greetings,
Tjerk

**Comment by nhoogendoorn** [comment]
Hey! I made a new release with this feature: [https://github.com/nhoogendoorn/CardStack/releases/tag/v0.1.2](https://github.com/nhoogendoorn/CardStack/releases/tag/v0.1.2)

You can now add a start index to the `StackConfiguration` initialiser, which in its turn sets the index in the `CardNavigation`. Let me know if this works for you!
